### ISSUE TITLE
About eval_fcot_on_otb.sh

### ISSUE THREAD

**Issue by leeyping** [MCG-NJU/FCOT#7]
Hi,thanks your excellent work. There are some problems when I run Eval_ fcot_ On_ otb.sh. It fails with the following error message:

Traceback (most recent call last):
  File "/home/xu/.conda/envs/fcot/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "../pytracking/benchmarks/ope_benchmark.py", line 52, in eval_success
    success_ret_[video.name] = success_overlap(gt_traj, tracker_traj, n_frame)
  File "/home/xu/.conda/envs/fcot/lib/python3.7/site-packages/numba/core/dispatcher.py", line 414, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/xu/.conda/envs/fcot/lib/python3.7/site-packages/numba/core/dispatcher.py", line 357, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
non-precise type array(pyobject, 0d, C)
During: typing of argument at ../pytracking/utils/vot_utils/statistics.py (104)

File "utils/vot_utils/statistics.py", line 104:
def success_overlap(gt_bb, result_bb, n_frame):
    thresholds_overlap = np.arange(0, 1.05, 0.05)
    ^

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_evaluation.py", line 52, in <module>
    tracker_params), desc='eval success', total=len(tracker_params), ncols=100):
  File "/home/xu/.conda/envs/fcot/lib/python3.7/site-packages/tqdm/std.py", line 1167, in __iter__
    for obj in iterable:
  File "/home/xu/.conda/envs/fcot/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
non-precise type array(pyobject, 0d, C)
During: typing of argument at ../pytracking/utils/vot_utils/statistics.py (104)

File "utils/vot_utils/statistics.py", line 104:
def success_overlap(gt_bb, result_bb, n_frame):
    thresholds_overlap = np.arange(0, 1.05, 0.05)

How I can fix this? I don't understand the error message.
If it was not right to open aan issue for my problem, I apologize.
I didn't know how to help myself anymore.

**Comment by jcaha** [comment]
It tends to report this error when there is no  results in the directory `pytracking/tracking_results/fcot/fcot_otb`. Please check the result files in this path. 
If so, you need to run our FCOT on OTB100 to generate tracking results first by running `bash/run_fcot_on_otb.sh`.

**Comment by leeyping** [comment]
Thank you for your reminder！ I checked the path and found that the path generated by run_fcot_on_otb.sh was not consistent with the one required by eval_fcot_on_otb.sh.  I changed the path and the problem was solved!
